name: Publish nightly release (reusable)
on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
      version-major-minor:
        required: true
        type: string
    secrets:
      base64-encoded-signingkey:
        required: true
jobs:
  call-build:
    uses: Yvand/AzureCP/.github/workflows/reusable-build.yml@master
    with:
      project-name: ${{ inputs.project-name }}
      version-major-minor: ${{ inputs.version-major-minor }}
    secrets:
      base64-encoded-signingkey: ${{ secrets.base64-encoded-signingkey }}

  nightly-release:
    needs: call-build
    runs-on: ubuntu-latest
    env:
      project-name: ${{ inputs.project-name }}
      assembly-version: ${{ needs.call-build.outputs.assembly-version }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./
          
      - name: Create zip files to publish
        run: |
          echo "assembly-version: ${{ env.assembly-version }}"
          mkdir ${{ env.project-name }}-symbols
          mkdir ${{ env.project-name }}-symbols/debug
          mkdir ${{ env.project-name }}-symbols/release
          echo "Generate symbols zip file"
          cp ./${{ env.project-name }}-Debug-symbols/* ${{ env.project-name }}-symbols/debug
          cp ./${{ env.project-name }}-Release-symbols/* ${{ env.project-name }}-symbols/release
          cd ${{ env.project-name }}-symbols
          zip -r ../${{ env.project-name }}-${{ env.assembly-version }}-symbols.zip ./*
          cd ..
          echo "Generate dependencies zip file"
          mkdir ${{ env.project-name }}-dependencies
          cp ./${{ env.project-name }}-Release-dependencies/* ${{ env.project-name }}-dependencies
          cd ${{ env.project-name }}-dependencies
          zip -r ../${{ env.project-name }}-${{ env.assembly-version }}-dependencies.zip ./*
          cd ..
      
      - name: Update nightly release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'Nightly Release $$'
          prerelease: true
          body: |
            This is a nightly release, use it with caution **and do not deploy it in a production environment**
          files: |
            ./${{ env.project-name }}-Release-wsp/${{ env.project-name }}.wsp
            ./${{ env.project-name }}-${{ env.assembly-version }}-symbols.zip
            ./${{ env.project-name }}-${{ env.assembly-version }}-dependencies.zip
